### ISSUE TITLE
edit BUNIT

### ISSUE THREAD

**Issue by andferrari** [JuliaAstro/FITSIO.jl#50]
Hi!,
If I create a header with the reserved key `BUNIT` and I save the file,
the key `BUNIT`  is not written in the header of the file.  Am I wrong somewhere ?

Thanks in advance

**Comment by kbarbary** [comment]
No, this is a problem with FITSIO.jl. `BUNIT` is included in the "reserved keywords" which are stripped when writing new headers. The reserved keywords are listed [here](https://github.com/JuliaAstro/FITSIO.jl/blob/1bd337ce570f4827b1852eb419a3c478bedceb84/src/header.jl#L129-L133). Most of these it makes sense to strip, because there are specific APIs for specifying them. For example, `SIMPLE`, `EXTEND` and `BITPIX` are written automatically when creating a new image - you wouldn't want to write them manually. However, this isn't the case for `BUNIT` - there's no other way to define it than the way you're doing. So I think `BUNIT` should simply be removed from the list of reserved keywords.

**Comment by kbarbary** [comment]
Closed by #51
